-- v1.2.1 schema extract - DDL ONLY, ZERO ROWS.
--
-- Generated by tools/baseline/archive-real-db.mjs on 2026-09-06.
-- Source: the sqlite_master table of a copy of the real, populated krono.db.
--
-- This file exists because D-03 forbids the database itself from entering this public
-- repository: it contains real client names and real work notes. Only the schema may be
-- committed. The generator selects nothing but type, name and sql from sqlite_master and
-- refuses to write this file if the result carries row data or a stray string literal.
--
-- D-05: this is the second of two schema sources. database/db.js holds the canonical
-- v1.2.1 DDL; this is what one real installation actually has. A difference between them
-- is not a bug to fix here - it is a second legacy variant that plan 01-07 and Phase 4
-- must migrate.
--
-- Do not hand-edit. Regenerate with: node tools/baseline/archive-real-db.mjs
-- Objects: 5 (table companies, table pomodoro_sessions, table settings, table sqlite_sequence, table work_sessions)

CREATE TABLE companies (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    , excel_column TEXT, note_column TEXT, note_required INTEGER DEFAULT 0);

CREATE TABLE pomodoro_sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      date TEXT NOT NULL,
      company_id INTEGER,
      pomodoros_completed INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
    );

CREATE TABLE settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE work_sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      duration INTEGER NOT NULL,
      date TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    , company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE, note TEXT);
